// <auto-generated />
using System;
using Combat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Combat.Infrastructure.Migrations
{
    [DbContext(typeof(CombatDbContext))]
    partial class CombatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Combat.Domain.Entities.CombatEncounter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndedAt");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Turns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Turns");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("Combats", (string)null);
                });

            modelBuilder.Entity("Combat.Domain.Entities.CombatEncounter", b =>
                {
                    b.OwnsOne("Combat.Domain.ValueObjects.Combatant", "Enemy", b1 =>
                        {
                            b1.Property<Guid>("CombatEncounterId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("EnemyId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("EnemyName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EnemyType");

                            b1.HasKey("CombatEncounterId");

                            b1.ToTable("Combats");

                            b1.WithOwner()
                                .HasForeignKey("CombatEncounterId");

                            b1.OwnsOne("Combat.Domain.ValueObjects.CombatantStats", "Stats", b2 =>
                                {
                                    b2.Property<Guid>("CombatantCombatEncounterId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Attack")
                                        .HasColumnType("integer")
                                        .HasColumnName("EnemyAttack");

                                    b2.Property<int>("Defense")
                                        .HasColumnType("integer")
                                        .HasColumnName("EnemyDefense");

                                    b2.Property<int>("Health")
                                        .HasColumnType("integer")
                                        .HasColumnName("EnemyHealth");

                                    b2.Property<int>("Speed")
                                        .HasColumnType("integer")
                                        .HasColumnName("EnemySpeed");

                                    b2.HasKey("CombatantCombatEncounterId");

                                    b2.ToTable("Combats");

                                    b2.WithOwner()
                                        .HasForeignKey("CombatantCombatEncounterId");
                                });

                            b1.Navigation("Stats")
                                .IsRequired();
                        });

                    b.OwnsOne("Combat.Domain.ValueObjects.Combatant", "Hero", b1 =>
                        {
                            b1.Property<Guid>("CombatEncounterId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("HeroId");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("HeroName");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("HeroType");

                            b1.HasKey("CombatEncounterId");

                            b1.ToTable("Combats");

                            b1.WithOwner()
                                .HasForeignKey("CombatEncounterId");

                            b1.OwnsOne("Combat.Domain.ValueObjects.CombatantStats", "Stats", b2 =>
                                {
                                    b2.Property<Guid>("CombatantCombatEncounterId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Attack")
                                        .HasColumnType("integer")
                                        .HasColumnName("HeroAttack");

                                    b2.Property<int>("Defense")
                                        .HasColumnType("integer")
                                        .HasColumnName("HeroDefense");

                                    b2.Property<int>("Health")
                                        .HasColumnType("integer")
                                        .HasColumnName("HeroHealth");

                                    b2.Property<int>("Speed")
                                        .HasColumnType("integer")
                                        .HasColumnName("HeroSpeed");

                                    b2.HasKey("CombatantCombatEncounterId");

                                    b2.ToTable("Combats");

                                    b2.WithOwner()
                                        .HasForeignKey("CombatantCombatEncounterId");
                                });

                            b1.Navigation("Stats")
                                .IsRequired();
                        });

                    b.Navigation("Enemy")
                        .IsRequired();

                    b.Navigation("Hero")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
