// <auto-generated />
using System;
using Heroes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Heroes.Infrastructure.Migrations
{
    [DbContext(typeof(HeroesDbContext))]
    partial class HeroesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Heroes.Domain.Entities.Hero", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Class");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("Experience");

                    b.Property<DateTime?>("LastBattleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastBattleAt");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("Name");

                    b.ToTable("Heroes", (string)null);
                });

            modelBuilder.Entity("Heroes.Domain.Entities.Hero", b =>
                {
                    b.OwnsOne("Heroes.Domain.ValueObjects.Stats", "CurrentStats", b1 =>
                        {
                            b1.Property<Guid>("HeroId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Attack")
                                .HasColumnType("integer")
                                .HasColumnName("Attack");

                            b1.Property<int>("Defense")
                                .HasColumnType("integer")
                                .HasColumnName("Defense");

                            b1.Property<int>("Health")
                                .HasColumnType("integer")
                                .HasColumnName("Health");

                            b1.Property<int>("Speed")
                                .HasColumnType("integer")
                                .HasColumnName("Speed");

                            b1.HasKey("HeroId");

                            b1.ToTable("Heroes");

                            b1.WithOwner()
                                .HasForeignKey("HeroId");
                        });

                    b.Navigation("CurrentStats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
